project_id = "rcefmfiqqqsfurkdljup"

[functions.send-sms]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-order-sms]
verify_jwt = false

[functions.sms-balance]
verify_jwt = false
